### ISSUE TITLE
Should portclippy support MY_DEPENDS?

### ISSUE THREAD

**Issue by 0mp** [t6/portfmt#10]
MY_DEPENDS is a variable that offers a way set BUILD_DEPENDS and RUN_DEPENDS to the same value without having to do the following:

```
BUILD_DEPENDS= a:b/c
RUN_DEPENDS:= ${BUILD_DEPENDS}
```

I am not sure, however, if it should really be supported by portclippy because I have a feeling that MY_DEPENDS is more of a hack and ordering it properly can differ between different ports.

Any opinions?

-----

Also, thanks a lot for this wonderful piece of software! It is a real gem!

**Comment by t6** [comment]
The framework itself is not really using `MY_DEPENDS`, so it is just a port local variable and IMHO it would be clearer to
1. just name it `_MY_DEPENDS` to mark it as such
2. just duplicate things in both `BUILD_DEPENDS` and `RUN_DEPENDS`
3. do it like in your example (which is perfectly fine)

Looking over [latest portscan results](https://pkg.tobik.me/portscan/portscan-latest.log), there are only 9 ports that currently use it. 

If it becomes more common, I'd be fine to adding it to the variable list however. I have already done this with the similar and ubiquitous `CRAN_DEPENDS`.

**Comment by 0mp** [comment]
> The framework itself is not really using `MY_DEPENDS`, so it is just a port local variable and IMHO it would be clearer to
> 
>     1. just name it `_MY_DEPENDS` to mark it as such
> 
>     2. just duplicate things in both `BUILD_DEPENDS` and `RUN_DEPENDS`
> 
>     3. do it like in your example (which is perfectly fine)

Option 3. works but it is not advised by the porter's handbook:

>    Do not use := to assign BUILD_DEPENDS to RUN_DEPENDS or vice-versa. All
>   variables are expanded immediately, which is exactly the wrong thing to do
>   and almost always a failure.

 
> Looking over [latest portscan results](https://pkg.tobik.me/portscan/portscan-latest.log), there are only 9 ports that currently use it.
> 
> If it becomes more common, I'd be fine to adding it to the variable list however. I have already done this with the similar and ubiquitous `CRAN_DEPENDS`.

I agree. Let's make it clear in the ports framework first and then teach portfmt about it if necessary!

**Comment by mat813** [comment]
MY_DEPENDS is not a thing.  I have been thinking about having a BUILD_RUN_DEPENDS variable for a while, I am still not sure I want us to have one because people. 
Until that happens, I think it would be preferable to not invent a variable name.

Or to do it properly:

```make
BUILD_DEPENDS=  ${RUN_DEPENDS} ...
RUN_DEPENDS=     ... 
```

The correct way is **NOT** to use `:=`, it does not do what you think it does. (Maybe _you_ know what it does, but the vast majority do not, so **please** do not use it.)

**Comment by 0mp** [comment]
> `MY_DEPENDS` is not a thing. I have been thinking about having a `BUILD_RUN_DEPENDS` variable for a while, I am still not sure I want us to have one because people.

Haha. ;)

> Until that happens, I think it would be preferable to not invent a variable name.
> 
> Or to do it properly:
> 
> ```makefile
> BUILD_DEPENDS=  ${RUN_DEPENDS} ...
> RUN_DEPENDS=     ... 
> ```

Hmmm, I see. So we care about not polluting run-time, but polluting build-time is somewhat ok (probably we do much less magic to RUN_DEPENDS than we do to BUILD_DEPDENDS).

**Comment by mat813** [comment]
Exactly, having a run-time only dependency leak into build depends is not a problem because:

1. Build dependencies are not registered by anything
2. They are going to be installed anyway before the package creation

**Comment by 0mp** [comment]
@mat813 Hmmm, we could think about updating the porter's handbook then.

Thanks, @mat & @t6 :)

**Comment by mat813** [comment]
> @mat813 Hmmm, we could think about updating the porter's handbook then.

What part of the porter's handbook?

**Comment by 0mp** [comment]
The one that encourages use of MY_DEPENDS.
