### ISSUE TITLE
OPTIONS_EXCLUDE_<xxx>

### ISSUE THREAD

**Issue by mat813** [t6/portfmt#11]
```diff
# Options definitions
OPTIONS_DEFINE
OPTIONS_DEFAULT
OPTIONS_EXCLUDE

-OPTIONS_EXCLUDE_${a}

OPTIONS_SUB
```
The OPTIONS_EXCLUDE_${a} is from:

```make
.for a in aarch64 arm armv6 armv7 \
	mips mips64 mips64el mips64elhf mips64hf mipsel mipselhf mipshf mipsn32 \
	powerpc powerpc64 powerpcspe \
	sparc64
OPTIONS_EXCLUDE_${a}=	DTRACE
.endfor
```

It is more or less at the right place, see Mk/bsd.options.mk:

```make
# OPTIONS_EXCLUDE		- List of options unsupported (useful for slave ports)
# OPTIONS_EXCLUDE_${ARCH}	- List of options unsupported on a given ${ARCH}
# OPTIONS_EXCLUDE_${OPSYS}	- List of options unsupported on a given ${OPSYS}
# OPTIONS_EXCLUDE_${OPSYS}_${OSREL:R} - List of options unsupported on a given
#				  ${OPSYS} and major version (11/12/13...)
```

I have not tried OPTIONS_EXCLUDE_amd64 or OPTIONS_EXCLUDE_FreeBSD_12, but I think some lattitude should be made with this.

**Comment by t6** [comment]
The reason for that there is no notion for expanding variables in portfmt's parser at the moment. Something simple (i.e, loop variables with only static words and with no modifiers) like your example might be feasible to expand at some point.

**Comment by mat813** [comment]
Well, you do not really need variable expansion, probably more like fuzzy matching `OPTIONS_EXCLUDE_${a}` looks a lot like `OPTIONS_EXCLUDE_something`, so it is probably ok.
Also, unless you hardcode all possible values of `ARCH`, `OPSYS`, `OSREL`, ..., you are going to have to do some fuzzy maching anyway.

**Comment by t6** [comment]
There are no shortcuts here. Misspelled vars like `OPTIONS_EXCLUDE_powrepc` need to be flagged. Or even `OPTIONS_EXCLUDE_sparc64` when we remove sparc64 from the list of valid archs.

For example, portfmt does some fuzzy matching for options/flavors helpers to find the right formatting rule, but portclippy is a lot more strict and actually looks up defined options and flavors to flag unhooked/useless helpers. To water this down is not a good direction to go in.
