### ISSUE TITLE
Options helpers and sorting

### ISSUE THREAD

**Issue by mat813** [t6/portfmt#12]
```make
# Options helpers
-DEBUG_CONFIGURE_ON
DEBUG_CONFIGURE_OFF
+DEBUG_CONFIGURE_ON
```

The "alphabetical sorting" cabal strikes again.  While it is true that `_OFF` is before `_ON` it is more logical, and easier to read when ON is before OFF.

A bit like, while you can write:

```c
if (!foo) {
  bar;
}
```

you do not write

```c
if (!foo) {
  bar;
} else {
  baz;
}
```

you write the one that is easier to read and understand:

```c
if (foo) {
  baz;
} else {
  bar;
}
```

**Comment by t6** [comment]
The order for options helpers and other variables is determined by [`variable_order_` in `rules.c` here](https://github.com/t6/portfmt/blob/47719c4156c460f7262e4d8b8c76981d4314cb0b/rules.c#L1343). You should open a PR to flip them around. Note that there is more on/off kind of things outside of options helpers like `CMAKE_OFF`, `CMAKE_ON` that would need to be flipped around as well. Some tests will probably need to be fixed too.

**Comment by mat813** [comment]
Well, this file looks awful 😝 

I'd say the `*_OFF` stuff has to go after `*_ON` (or `*` when it's not called `*_ON`).
