### ISSUE TITLE
more on options helpers ordering

### ISSUE THREAD

**Issue by mat813** [t6/portfmt#13]
```diff
# Options helpers
-GDBM_CONFIGURE_ON
-GDBM_CONFIGURE_OFF
GDBM_LIB_DEPENDS
+GDBM_CONFIGURE_OFF
+GDBM_CONFIGURE_ON
```

I don't know about you, but LIB is after CONFIGURE in my alphabet.

See https://www.freebsd.org/doc/en/books/porters-handbook/porting-order-options.html

**Comment by t6** [comment]
So what do you think the right order is?

Alphabetically sorted it would be
```
GDBM_CONFIGURE_OFF
GDBM_CONFIGURE_ON
GDBM_LIB_DEPENDS
```
but then there is #12 where you say something else.

Outside of options helpers, we declare dependencies first and only then describe how to configure them (LIB_DEPENDS < USES < CONFIGURE_ARGS).

**Comment by mat813** [comment]
Well, in #12 and #13 I say things along the same lines.
The order should be:

```
GDBM_CONFIGURE_ON
GDBM_CONFIGURE_OFF
GDBM_LIB_DEPENDS
GDBM_USES
```

Rereading [15.10. Options and Helpers](https://www.freebsd.org/doc/en/books/porters-handbook/porting-order-options.html), what was meant by:

>  Try and sort all of those alphabetically.

was about sorting by option names, like, put the `GDBM_*` after the `DEBUG_*`, but it was not really about the helpers themselves.

Sorting things alphabetically is fine and all from a computer's point of view, but it does not make much sense from a human brain point of view. It makes more sense to put the YES before the NO. Same reason we try very hard to not have options that disable a feature, we do not have a `NOGDBM` option that has:

```make
NOGDBM_CONFIGURE_ON=  --without-gdbm
NOGDBM_CONFIGURE_OFF=  --with-gdbm
```

It has double negatives, which are harder for the human brain to grasp, so, we have a `GDBM` option that has things turned the "right" way.

Now, this is only about options helpers.  If later we have a block with:

```make
.if ${PORT_OPTIONS:MGDBM}
blah
.endif
```

Then we probably want to *_DEPENDS, then USES, then the rest.

**Comment by mat813** [comment]
To comment a bit more on this, the reason I wrote [Chapter 15. Order of Variables in Port Makefiles](https://www.freebsd.org/doc/en/books/porters-handbook/porting-order.html) was so that to make things easier for humans. All ports have a "right way" to be written, with things in a somewhat logical order.
It is so that anyone can grab any port and not be lost and wondering, why the fuck did they write the Makefile that way, is there a reason, or...

Like the battle I have with people who keep using `+=` when the variable is not defined before. It is bad because when someone else reads the Makefile, they are left wondering, is there a slave port, was there a slave port, was there something else before, is it some special case...

I often quote bits of wisdom from [The Elements of Programming Style](https://en.wikipedia.org/wiki/The_Elements_of_Programming_Style), even if the book was written more than 40 years ago, it still makes sense, like:

1. Write clearly -- don't be too clever.
2. Say what you mean, simply and directly.
3. Use library functions whenever feasible.
4. Avoid too many temporary variables.
5. Write clearly -- don't sacrifice clarity for efficiency.
6. Let the machine do the dirty work.

In the first 6 points, 1, 2 and 5 say the same thing, write it so that the you from 5 years in the future won't spend half an hour wondering wtf.
