### ISSUE TITLE
Allow COMMENT_<flavor> below COMMENT?

### ISSUE THREAD

**Issue by Jehops** [t6/portfmt#15]
In `editors/emacs-devel` (and some other ports with flavors), a way to update the comment when a non-default flavor is chosen is like this.

```
MAINTAINER=	emacs@FreeBSD.org

COMMENT=	GNU editing macros ${COMMENT_${FLAVOR}}
COMMENT_nox=	(No X flavor)
```
Could `portclippy` allow `COMMENT_nox` just below `COMMENT`?

This seems slightly cleaner than calling the  variable `_COMMENT_nox`, or putting it near the bottom of the file.

**Comment by t6** [comment]
It would be better to lobby for adding proper support for a `COMMENT_flavor` helper to the framework first before making portclippy accept it. It seems like appending to COMMENT for a flavor is something multiple ports are doing now. Enough to justify that IMHO. See https://reviews.freebsd.org/D30592 which seems to have been abandoned without a fight unfortunately.
