### ISSUE TITLE
-U should not sort COMMENT and CATEGORIES

### ISSUE THREAD

**Issue by mirror176** [t6/portfmt#16]
Ran `portfmt -UD Makefile` after working through without -U to help me clean up some old porting efforts on unreleased ports and after working through the other issues, I found these were the last two things listed for editing. Sorting the COMMENT alphabetically would make it not useful and CATEGORIES should be sorted per porters  handbook 5.3.3 and not just alphabetically.

**Comment by t6** [comment]
`-U` forces on sorting for every variable even when portfmt thinks it shouldn't. `-U` is only useful for parts of a Makefile, never the whole one.
