### ISSUE TITLE
macOS compilation warning

### ISSUE THREAD

**Issue by grylem** [t6/portfmt#4]
Two warning when compiled on macOS
compats.c:122:8: warning: implicit declaration of function 'memset_s' is invalid in C99 [-Wimplicit-function-declaration]
        (void)memset_s(p, n, 0, n);

compats.c:122:8: warning: this function declaration is not a prototype [-Wstrict-prototypes]

Regards.

**Comment by t6** [comment]
This seems harmless to me. Can you submit a pull request to fix it? Otherwise this will probably be left as is since I do not have access to a macOS installation beyond the Travis CI environment.

**Comment by grylem** [comment]
if i add string
errno_t memset_s(void *, rsize_t, int, rsize_t);
to config.h portfmt compiled without warnings.
Also if you have time please read
https://github.com/Aversiste/pnginfo/issues/1
there the same problem was solved

**Comment by t6** [comment]
> if i add string
> errno_t memset_s(void *, rsize_t, int, rsize_t);
> to config.h portfmt compiled without warnings.

I do not think this is correct. It just silences the warning while not solving the problem. Why does string.h not have that prototype on macOS?

> Also if you have time please read
> Aversiste/pnginfo#1
> there the same problem was solved

I do not see a resolution to the problem there. AFAICT all they did is remove the memset_s compat code. Problem is that portfmt is using it via recallocarray via explicit_bzero, so that is a no-go.

**Comment by grylem** [comment]
Maybe its?
from manpage memset_s
#define __STDC_WANT_LIB_EXT1__ 1
add this string  to compats.c - no any warnings
This is correct way?

**Comment by t6** [comment]
If that solves the problem then I'd be fine with it. Can you please open a pull request, so that we can get CI confirmation of it?

**Comment by grylem** [comment]
> If that solves the problem then I'd be fine with it.

Yes it solves the problem.

> Can you please open a pull request, so that we can get CI confirmation of it?

I'm sorry but I don't know how to do it

**Comment by t6** [comment]
:-(

Fixed in 27f1c4141ea5ad23f964d289cf8a0de2370e0571 via #5.
